### ISSUE TITLE
ERROR: bash: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by Crazygiscool** [pterodactyl-installer/pterodactyl-installer#510] opened 2024-10-13 17:19 UTC
**Describe the bug**
when executing the installation script, give 'bash: /dev/fd/63: No such file or directory' error

**To Reproduce**
Steps to reproduce the behaviour:
proxmox scsi0 drive
1. type 'cd'
2. type script 'bash <(curl -s https://pterodactyl-installer.se)'

**Expected behaviour**
installation of the panel

**OS (please complete the following information):**

- OS: Ubuntu Server 24.04
- Installation: panel

**Comment by Linux123123** [comment] 2024-10-17 12:05
Use `sudo su` or `sudo -i` before running the script.

**Comment by SebRHQ** [comment] 2024-10-18 17:43
Hi! Im having the same thing, sudo -i or sudo su does not fix the problem for me

**Comment by Tbizla** [comment] 2024-10-21 01:32
Same boat,

`sudo` su and `sudo -i` didn't work for me

**Comment by vilhelmprytz** [comment] 2024-10-21 08:49
Duplicate of #1, #29, #171, #205, #246, #311, #355, #386, #403, #441, #453, #460, #463 and #508 🙂 I probably missed a few other issues. Feel free to reopen if this is not the case.

**Closed by vilhelmprytz** 2024-10-21 08:49 UTC

**Comment by Crazygiscool** [comment] 2024-10-22 21:35
tysm guys, I used https://pterodactyl-installer.se/i.sh and it worked
