### ISSUE TITLE
curl: (23) Failure writing output to destination

### ISSUE THREAD

**Issue by Dany01000110** [pterodactyl-installer/pterodactyl-installer#359] opened 2022-12-01 23:09 UTC
**Describe the bug**
When I want to select option n°2, I get the error `curl: (23) Failure writing output to destination`

**To Reproduce**
Steps to reproduce the behaviour:

1. Have Debian 11
2. Execute script
3. Select third option (both option of installation)

**Expected behaviour**
It should install the two previous options in the list (wings script and panel).

**Screenshots**
[Screenshot here. (https://img.dany01000110.xyz/images/2022/12/02/81b6c2773a45e2950b9239d58f6468cb.png)](https://img.dany01000110.xyz/images/2022/12/02/81b6c2773a45e2950b9239d58f6468cb.png)

**OS (please complete the following information):**

- OS: Debian 11
- Installation: Both (Panel and Wings)

**Comment by ehamawy** [comment] 2022-12-02 06:20
Getting the same error on a fresh Ubuntu 22.04 LTS

**Comment by vilhelmprytz** [comment] 2022-12-02 07:40
@Linux123123, do you know anything about this?

**Comment by Dokman** [comment] 2022-12-02 10:18
doesn't work

**Comment by vilhelmprytz** [comment] 2022-12-02 10:34
> doesn't work

Please elaborate. What's not working? What's the error message?

**Comment by Dany01000110** [comment] 2022-12-02 10:48
> > doesn't work
> 
> Please elaborate. What's not working? What's the error message?

Same error : `curl: (23) Failure writing output to destination` :/

**Comment by Dokman** [comment] 2022-12-02 11:16
> > doesn't work
> 
> Please elaborate. What's not working? What's the error message?

i mean if i use the command that you send it gaves me the same error
![image](https://user-images.githubusercontent.com/2290904/205280828-25104f5f-0c47-44da-9537-eb9fda235e97.png)

**Comment by MohmadHafiz** [comment] 2022-12-02 13:44
not working :/ 
![image](https://user-images.githubusercontent.com/18700288/205306434-3b42f2fd-5399-4a7c-9847-ef79fd50f338.png)

**Comment by vilhelmprytz** [comment] 2022-12-02 17:08
To anyone that has this problem: can you please try to run the script and select options `3`, `4`, or `5`?

**Comment by FlashSkyNews** [comment] 2022-12-02 17:18
5 dosen't work too, same error

**Comment by vilhelmprytz** [comment] 2022-12-02 17:19
Can you do `curl https://pterodactyl-installer.se` just to see that it actually pulls the latest version? I just pushed another commit that actually made the changes I initially push "go live".

**Comment by vilhelmprytz** [comment] 2022-12-02 17:21
Also, feel free to join [our Discord server](https://pterodactyl-installer.se/discord) for easier communication since we're not able to reproduce this problem ourselves.

**Comment by Dany01000110** [comment] 2022-12-02 18:43
Here is a resolution provided by linux123123 which solved the problem for me:

**Steps to solve the problem:**

1. Run `rm -rf /tmp/lib.sh`
2. Retry to execut `bash <(curl -s https://pterodactyl-installer.se)` script
3. It's done!

**Comment by Linux123123** [comment] 2022-12-02 19:21
It is fully fixed by https://github.com/pterodactyl-installer/pterodactyl-installer/tree/2bb8695c5fec5377915aa9346410c91e5132f0d6 and https://github.com/pterodactyl-installer/pterodactyl-installer/tree/f82954a448268dcb0d9eb6d4d092a9a37e299602. Thanks, @Dany01000110, for reporting and testing.

**Closed by Linux123123** 2022-12-02 19:21 UTC
Labels: bug
