### ISSUE TITLE
Web server selection

### ISSUE THREAD

**Issue by KneesDev** [pterodactyl-installer/pterodactyl-installer#434] opened 2023-09-07 16:20 UTC
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem.

**Describe the solution you'd like**
It would be great if the script allowed us to choose what web server to use (nginx or Apache) since Pterodactyl supports both.

**Describe alternatives you've considered**
Just using nginx I guess?

**Comment by Linux123123** [comment] 2023-09-07 16:22
Duplicate of #327

**Closed** 2023-09-07 16:22 UTC
