### ISSUE TITLE
Please allow this installer to be installed on Ubuntu 23.04

### ISSUE THREAD

**Issue by rizal333** [pterodactyl-installer/pterodactyl-installer#443] opened 2023-10-28 13:07 UTC
I can't install the panel with this installer on Ubuntu 23.04 for reasons of unsupported OS. Please fix it immediately and make it compatible.

**Comment by Linux123123** [comment] 2023-10-28 13:09
Duplicate of #440

**Closed** 2023-10-28 13:10 UTC
