### ISSUE TITLE
README says Ubuntu 24.04 is support. Script says Ubuntu 24.04 is unsupported...

### ISSUE THREAD

**Issue by F1zzyD** [pterodactyl-installer/pterodactyl-installer#493] opened 2024-07-05 07:50 UTC
**Describe the bug**
When running the script, it says Ubuntu 24.04 is unsupported, even though the README says Ubuntu 24.04 is supported

**To Reproduce**
1. Run the script bash <(curl -s https://pterodactyl-installer.se)
(small note, no where on the github page does it say to run "sudo su" before running the command. Just FYI)
2. Select 0 or 1 to install
3. Error

**Expected behaviour**
Install?

**OS (please complete the following information):**
Ubuntu 24.04

**Comment by WhyYum** [comment] 2024-07-05 12:12
Try this:
wget -O install.sh https://pterodactyl-installer.se

Then run the script and see the error "not supported".
After that, edit the lines in the install.sh file:
export GITHUB_SOURCE="v1.0.0"
export SCRIPT_RELEASE="v1.0.0"
to
export GITHUB_SOURCE="master"
export SCRIPT_RELEASE="master"

Then run: bash install.sh

The problem is that it takes the old file https://raw.githubusercontent.com/pterodactyl-installer/pterodactyl-installer/v1.0.0/lib/lib.sh instead of the current one https://raw.githubusercontent.com/pterodactyl-installer/pterodactyl-installer/master/lib/lib.sh

Literally need a release to create a repository owner and everything will be fixed.

**Closed** 2024-07-10 15:08 UTC
